sudo: required

services:
  - docker

before_install:
  - docker build -t lostark78/multi-react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true lostark78/multi-react-test npm run test

after_success:
  - docker build -t lostark78/multi-client ./client
  - docker build -t lostark78/multi-server ./server
  - docker build -t lostark78/multi-nginx ./nginx
  - docker build -t lostark78/multi-worker ./worker
#login to docker-cli

##depoy to docker-hub

